### ISSUE TITLE
Unicode chars

### ISSUE THREAD

**Issue by bAndie91** [ygoe/T-Clock#4]
it'd be good to have unicode chars, symbols on the clock display.
i tested these on Win10 with several fonts (Calibri, Arial, Times, W*dings)
* U+1F4C5 CALENDAR 📅 
* U+231A WATCH ⌚

but always resulting in question marks on the screen.

**Comment by bAndie91** [comment]
nevermind, https://github.com/White-Tiger/T-Clock/ supports it

**Comment by ygoe** [comment]
Yeah, that's the official repository today. Mine was just a temporary thing. I should probably delete it.
